name: This custom workflow is trigger via HTTP 
on: 
  repository_dispatch:
    types: [dump_context]
jobs:
  dumpContext:
    name: Dump context and payload
    runs-on: [ubuntu-latest]
    - steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump payload
        env:
          PAYLOAD: ${{ github.event.body }}"
        run: echo "$PAYLOAD"
      
